// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY9nhIPOR8nk9t5Rqv4ky051wOKhe-nyM',
    appId: '1:650952094067:web:ee2ac1ca79f16b70f81506',
    messagingSenderId: '650952094067',
    projectId: 'poketroguemon',
    authDomain: 'poketroguemon.firebaseapp.com',
    storageBucket: 'poketroguemon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN-ibZhs0jfJnYvMMa7bcvFQMYElgr1zs',
    appId: '1:650952094067:android:810b380a8e00579df81506',
    messagingSenderId: '650952094067',
    projectId: 'poketroguemon',
    storageBucket: 'poketroguemon.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHuD687XvCRy0PZwUYm9MF2AntrI8J1_g',
    appId: '1:650952094067:ios:810bd62d41fd0342f81506',
    messagingSenderId: '650952094067',
    projectId: 'poketroguemon',
    storageBucket: 'poketroguemon.firebasestorage.app',
    androidClientId: '650952094067-3rutn6bcnn47bikv991o2i3r2tacf749.apps.googleusercontent.com',
    iosClientId: '650952094067-0vgj92ee6883qvva5t01no5ll0cdugtf.apps.googleusercontent.com',
    iosBundleId: 'com.example.poketroguemon',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHuD687XvCRy0PZwUYm9MF2AntrI8J1_g',
    appId: '1:650952094067:ios:810bd62d41fd0342f81506',
    messagingSenderId: '650952094067',
    projectId: 'poketroguemon',
    storageBucket: 'poketroguemon.firebasestorage.app',
    androidClientId: '650952094067-3rutn6bcnn47bikv991o2i3r2tacf749.apps.googleusercontent.com',
    iosClientId: '650952094067-0vgj92ee6883qvva5t01no5ll0cdugtf.apps.googleusercontent.com',
    iosBundleId: 'com.example.poketroguemon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY9nhIPOR8nk9t5Rqv4ky051wOKhe-nyM',
    appId: '1:650952094067:web:7fd8ec77d6dcfe1df81506',
    messagingSenderId: '650952094067',
    projectId: 'poketroguemon',
    authDomain: 'poketroguemon.firebaseapp.com',
    storageBucket: 'poketroguemon.firebasestorage.app',
  );
}
